import { test, expect, type Page } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL, key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
test.skip(process.env.E2E_RUN!=="true"||!url||!key,"requires isolated Supabase E2E project with schema.sql and seed.sql applied");

async function setup(page:Page){const client=createClient(url!,key!);const email=`execution-${Date.now()}-${Math.random().toString(36).slice(2)}@example.test`;const password="A-test-password-123";const {data,error}=await client.auth.signUp({email,password});if(error||!data.session)throw new Error(error?.message??"Disable email confirmation in the isolated project");const a={chestPain:false,dizziness:false,jointProblem:false,cardiacMedication:false,doctorRestriction:false,pregnancy:false,otherReason:false};const {error:onboard}=await client.rpc("complete_onboarding",{p_name:"Execution Test",p_age:30,p_height_cm:170,p_weight_kg:70,p_sex:"",p_units:"metric",p_goal:"general_fitness",p_experience_level:"beginner",p_equipment:["bodyweight"],p_workout_location:"home",p_days_per_week:1,p_session_duration_minutes:30,p_parq_answers:a,p_professional_clearance_ack:false,p_contraindications:[]});if(onboard)throw onboard;const day=[{day_number:1,focus:"Full body",estimated_duration_minutes:20,exercises:[{exercise_id:"10000000-0000-4000-8000-000000000001",name:"Bodyweight squat",instructions:"Perform Bodyweight squat with controlled form.",sets:2,rep_min:8,rep_max:12,rest_seconds:30,order_index:0}]}];const {data:planId,error:planError}=await client.rpc("persist_generated_workout_plan",{p_generator_version:"deterministic-v1",p_days:day});if(planError)throw planError;const {data:workoutDay}=await client.from("workout_days").select("id").eq("plan_id",planId).single();if(!workoutDay)throw new Error("Workout day was not persisted");await page.goto("/login");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();return {client,dayId:workoutDay.id};}

test("home navigates through overview, starts and resumes a session",async({page})=>{const {dayId}=await setup(page);await page.getByRole("link",{name:"View workout"}).click();await expect(page).toHaveURL(new RegExp(`/workout/${dayId}/overview`));await page.getByRole("link",{name:/Start workout/i}).click();await expect(page).toHaveURL(new RegExp(`/workout/${dayId}$`));await page.reload();await expect(page.getByRole("button",{name:"Complete Set"})).toBeVisible();});

test("execution persists actual set inputs, rest controls, skips, and completes",async({page})=>{const {client,dayId}=await setup(page);await page.goto(`/workout/${dayId}`);await page.getByLabel("Actual weight").fill("42.5");await page.getByLabel("Actual reps").fill("10");await page.getByLabel("RPE").fill("7");await page.getByRole("button",{name:"Complete Set"}).click();await expect(page.getByText("Rest")).toBeVisible();await page.getByRole("button",{name:"Pause"}).click();await page.getByRole("button",{name:"+30s"}).click();await page.getByRole("button",{name:"Skip"}).click();const {data:session}=await client.from("workout_sessions").select("id").eq("workout_day_id",dayId).eq("status","in_progress").single();if(!session)throw new Error("Workout session was not created");const {data:sets}=await client.from("exercise_sets").select("reps,weight_kg,rpe").eq("session_id",session.id);expect(sets).toEqual(expect.arrayContaining([expect.objectContaining({reps:10,weight_kg:42.5,rpe:7})]));await page.getByRole("button",{name:"Finish workout"}).click();await expect(page).toHaveURL(new RegExp(`/workout/summary/${session.id}`));await expect(page.getByText("Workout Complete")).toBeVisible();});
