import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";

const url=process.env.NEXT_PUBLIC_SUPABASE_URL, key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
test.skip(process.env.E2E_RUN!=="true"||!url||!key,"requires an isolated Supabase project with schema.sql and seed.sql applied");
async function setup(){const client=createClient(url!,key!);const email=`plan-${Date.now()}-${Math.random().toString(36).slice(2)}@example.test`;const {data,error}=await client.auth.signUp({email,password:"A-test-password-123"});if(error||!data.user||!data.session)throw new Error(error?.message??"Disable email confirmation for E2E");const answers={chestPain:false,dizziness:false,jointProblem:false,cardiacMedication:false,doctorRestriction:false,pregnancy:false,otherReason:false};const {error:setupError}=await client.rpc("complete_onboarding",{p_name:"Plan Test",p_age:30,p_height_cm:170,p_weight_kg:70,p_sex:"",p_units:"metric",p_goal:"general_fitness",p_experience_level:"beginner",p_equipment:["bodyweight"],p_workout_location:"home",p_days_per_week:1,p_session_duration_minutes:30,p_parq_answers:answers,p_professional_clearance_ack:false,p_contraindications:[]});if(setupError)throw setupError;return {client,id:data.user.id};}
const valid=[{day_number:1,focus:"Full body",estimated_duration_minutes:20,exercises:[{exercise_id:"10000000-0000-4000-8000-000000000001",name:"Bodyweight squat",instructions:"Perform Bodyweight squat with controlled form.",sets:2,rep_min:8,rep_max:12,rest_seconds:60,order_index:0}]}];
test("atomic RPC persists a valid plan using a seeded exercise",async()=>{const {client}=await setup();const {data,error}=await client.rpc("persist_generated_workout_plan",{p_generator_version:"deterministic-v1",p_days:valid});expect(error).toBeNull();expect(data).toBeTruthy();const {data:days}=await client.from("workout_days").select("id").eq("plan_id",data);expect(days).toHaveLength(1);});
test("atomic RPC rolls back its parent plan when a child is invalid",async()=>{const {client,id}=await setup();const {count:before}=await client.from("workout_plans").select("id",{count:"exact",head:true}).eq("user_id",id);const bad=structuredClone(valid);bad[0].exercises[0].exercise_id="00000000-0000-4000-8000-000000000000";const {error}=await client.rpc("persist_generated_workout_plan",{p_generator_version:"deterministic-v1",p_days:bad});expect(error).not.toBeNull();const {count:after}=await client.from("workout_plans").select("id",{count:"exact",head:true}).eq("user_id",id);expect(after).toBe(before);});
